PIN_CODE_TEXT = "please type pin code for access to closed function this bot\n<b>PIN:</b> "
SUCCESS_TEXT = "PIN code is <b>valid</b>, welcome"
ERROR_TEXT = "\n<i>PIN code is <b>not valid</b>, try again</i>"
CLEAN_FIELD_TEXT = "\n<i>cleaned, try again</i>"
CLOSE_TEXT = "PIN keypad closed"
